SALES:
  target: dev
  outputs:
    dev:
      type: postgres
      user: postgres
      password: ky1213141516
      host: localhost
      threads: 4
      port: 3000
      dbname: postgres
      schema: public