SALES: # profile name
  target: dev # default postgres server in dbt
  outputs:
    dev:
    # If your postgres server is localhost:3000
      type: postgres
      user: postgres
      password: ky1213141516
      host: localhost
      threads: 4
      port: 3000
      dbname: postgres
      schema: public